# Generated by Django 5.0.7 on 2024-07-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_dadospaciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadospaciente',
            name='data',
            field=models.DateField(),
        ),
    ]
