# Generated by Django 5.0.7 on 2024-07-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_refeicao_opcao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='opcao'),
        ),
    ]
